### ISSUE TITLE
Failed to Load the ResxPackage in Visual Studio 2017

### ISSUE THREAD

**Issue by kwomba** [stefanegli/ResxFormatter#7]
**Describe the bug**
I get the following error in the ActivityLog when loading the ResxFormatter package (2.0.68)

```
<description>
SetSite failed for package [ResxFormatterPackage]Source:'Microsoft.VisualStudio.Shell.15.0' Description: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.
System.InvalidOperationException: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.
 at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType)
 at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(Type serviceType)
 at Microsoft.VisualStudio.Shell.Package.PackageContainer.GetService(Type serviceType)
 at System.ComponentModel.Container.Site.GetService(Type service)
 at System.ComponentModel.Component.GetService(Type service)
 at Microsoft.VisualStudio.Shell.DialogPage.get_SettingsManager()
 at Microsoft.VisualStudio.Shell.DialogPage.LoadSettingsFromStorage()
 at Microsoft.VisualStudio.Shell.DialogPage.set_Site(ISite value)
 at System.ComponentModel.Container.Add(IComponent component, String name)
 at System.ComponentModel.Container.Add(IComponent component)
 at Microsoft.VisualStudio.Shell.Package.GetDialogPage(Type dialogPageType)
 at ResxFormatter.ResxFormatterPackage.get_Settings()
 at ResxFormatter.ResxFormatterPackage.<InitializeAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass17_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__78.MoveNext()</description>
```

**To Reproduce**
Just install the package in Visual Studio 2017 using vsixinstaller

**Expected behavior**
No error when package loading

**Screenshots**
![image](https://user-images.githubusercontent.com/13519180/176408346-68c33452-4076-44db-a958-8c0aacbdaa8a.png)

**Desktop (please complete the following information):**
Windows 10

**Smartphone (please complete the following information):**
N/A

**Additional context**
Just add the following statement (as first statement) to the ```protected override async Task InitializeAsync(....) ``` (ResxFormatterPackage.cs):
```
            await this.JoinableTaskFactory.SwitchToMainThreadAsync(cancellationToken);
```

**Comment by stefanegli** [comment]
I forgot about the "git commit actions". I did not really intend to close the issue yet. You can try the latest CI build:
https://www.vsixgallery.com/extension/ResxFormatter.61507132-4401-47b1-9950-575e43b964c6/

I do not have VS2017 installed anymore and I do not have time to really investigate why it is not working with this version. I did however remove the "offending" line of code. Maybe that is already enough :-)

Please note: This version requires to make settings by the EditorConfig file, otherwise your files remain untouched.

**Comment by kwomba** [comment]
This does fix the issue described.

**Comment by stefanegli** [comment]
Thanks for the quick feedback. Stay tuned for the proper release of this version... might take a moment though :-)
